import { CreateBankDto } from './create-bank.dto';

// Logos are downloaded to the frontend at build time and served locally
// (frontend/public/banks/<domain>.png) so they always render — no external
// dependency. Banks without a real logo fall back to a coloured initials avatar.
const logo = (domain: string) => `/banks/${domain}.png`;

const V = 'Visa';
const M = 'Mastercard';
const J = 'JCB';
const A = 'Amex';
const U = 'UnionPay';

export const VIETNAMESE_BANKS: CreateBankDto[] = [
  {
    code: 'VCB',
    name: 'Vietcombank',
    fullName: 'Ngân hàng TMCP Ngoại thương Việt Nam',
    logo: logo('vietcombank.com.vn'),
    color: '#007E3F',
    description: 'Ngân hàng Ngoại thương Việt Nam',
    website: 'https://www.vietcombank.com.vn',
    hotline: '1900545413',
    cardBrands: [V, M, A, U, J],
    creditCards: [
      'Vietcombank Visa Signature',
      'Vietcombank Cashback Plus American Express',
      'Vietcombank Mastercard World',
      'Vietcombank Visa Platinum',
      'Vietcombank JCB',
    ],
  },
  {
    code: 'BIDV',
    name: 'BIDV',
    fullName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    logo: logo('bidv.com.vn'),
    color: '#00558C',
    description: 'Ngân hàng Đầu tư và Phát triển Việt Nam',
    website: 'https://www.bidv.com.vn',
    hotline: '1900969696',
    cardBrands: [V, M, J],
    creditCards: [
      'BIDV Visa Platinum',
      'BIDV Premier World Mastercard',
      'BIDV Visa Flexi',
      'BIDV Vietravel Visa',
      'BIDV Smile Card',
    ],
  },
  {
    code: 'CTG',
    name: 'VietinBank',
    fullName: 'Ngân hàng TMCP Công thương Việt Nam',
    logo: logo('vietinbank.vn'),
    color: '#0072BC',
    description: 'Ngân hàng Công thương Việt Nam',
    website: 'https://www.vietinbank.vn',
    hotline: '1900558868',
    cardBrands: [V, M, J],
    creditCards: [
      'VietinBank Visa Platinum Cashback',
      'VietinBank Premium Banking',
      'VietinBank JCB Ultimate',
      'VietinBank Mastercard',
    ],
  },
  {
    code: 'Agribank',
    name: 'Agribank',
    fullName: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    logo: logo('agribank.com.vn'),
    color: '#9B1C1F',
    description: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    website: 'https://www.agribank.com.vn',
    hotline: '1900558818',
    cardBrands: [V, M, J],
    creditCards: ['Agribank Visa Platinum', 'Agribank Lộc Việt', 'Agribank JCB'],
  },
  {
    code: 'TCB',
    name: 'Techcombank',
    fullName: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    logo: logo('techcombank.com.vn'),
    color: '#EC1C24',
    description: 'Ngân hàng Kỹ thương Việt Nam',
    website: 'https://www.techcombank.com.vn',
    hotline: '1800588822',
    cardBrands: [V, M],
    creditCards: [
      'Techcombank Visa Signature',
      'Techcombank Spark',
      'Techcombank Visa Priority',
      'Techcombank Style',
      'Techcombank Bến Thành',
    ],
  },
  {
    code: 'MB',
    name: 'MB Bank',
    fullName: 'Ngân hàng TMCP Quân đội',
    logo: logo('mbbank.com.vn'),
    color: '#1F4E8C',
    description: 'Ngân hàng Thương mại Quân đội',
    website: 'https://www.mbbank.com.vn',
    hotline: '1900545426',
    cardBrands: [V, M, J, U],
    creditCards: [
      'MB Visa Hi Collection',
      'MB JCB Sakura',
      'MB Visa Online Shopping',
      'MB Mastercard',
    ],
  },
  {
    code: 'VPB',
    name: 'VPBank',
    fullName: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    logo: logo('vpbank.com.vn'),
    color: '#00A04A',
    description: 'Ngân hàng Việt Nam Thịnh Vượng',
    website: 'https://www.vpbank.com.vn',
    hotline: '1900545415',
    cardBrands: [V, M],
    creditCards: [
      'VPBank StepUp',
      'VPBank Lady',
      'VPBank Shopee Platinum',
      'VPBank Diamond World',
      'VPBank Z Gen',
      'VPBank Visa Platinum Travel Miles',
    ],
  },
  {
    code: 'ACB',
    name: 'ACB',
    fullName: 'Ngân hàng TMCP Á Châu',
    logo: logo('acb.com.vn'),
    color: '#005FAA',
    description: 'Ngân hàng Thương mại Á Châu',
    website: 'https://www.acb.com.vn',
    hotline: '1900545486',
    cardBrands: [V, M, J],
    creditCards: [
      'ACB Visa Privilege Signature',
      'ACB Express',
      'ACB Visa Platinum',
      'ACB JCB',
      'ACB Mastercard',
    ],
  },
  {
    code: 'STB',
    name: 'Sacombank',
    fullName: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    logo: logo('sacombank.com.vn'),
    color: '#003DA5',
    description: 'Ngân hàng Sài Gòn Thương Tín',
    website: 'https://www.sacombank.com.vn',
    hotline: '1900555588',
    cardBrands: [V, M, J],
    creditCards: [
      'Sacombank Visa Signature',
      'Sacombank Mastercard Platinum',
      'Sacombank JCB Ultimate',
      'Sacombank Visa Cashback',
    ],
  },
  {
    code: 'HDB',
    name: 'HDBank',
    fullName: 'Ngân hàng TMCP Phát triển TP. Hồ Chí Minh',
    logo: logo('hdbank.com.vn'),
    color: '#ED1B2E',
    description: 'Ngân hàng Phát triển TP. Hồ Chí Minh',
    website: 'https://www.hdbank.com.vn',
    hotline: '19006060',
    cardBrands: [V, M, J],
    creditCards: [
      'HDBank Visa Platinum',
      'HDBank Vietjet Platinum',
      'HDBank Flex',
      'HDBank Petrolimex 4in1',
    ],
  },
  {
    code: 'VIB',
    name: 'VIB',
    fullName: 'Ngân hàng TMCP Quốc tế Việt Nam',
    logo: logo('vib.com.vn'),
    color: '#00467F',
    description: 'Ngân hàng Quốc tế Việt Nam',
    website: 'https://www.vib.com.vn',
    hotline: '18008180',
    cardBrands: [V, M],
    creditCards: [
      'VIB Online Plus 2in1',
      'VIB Cash Back',
      'VIB Premier Boundless',
      'VIB Travel Élite',
      'VIB Financial Free',
      'VIB Rewards Unlimited',
    ],
  },
  {
    code: 'TPB',
    name: 'TPBank',
    fullName: 'Ngân hàng TMCP Tiên Phong',
    logo: logo('tpb.vn'),
    color: '#5A2D81',
    description: 'Ngân hàng Tiên Phong',
    website: 'https://www.tpb.vn',
    hotline: '1900585885',
    cardBrands: [V, M, J],
    creditCards: [
      'TPBank Visa FreeGo',
      'TPBank Visa Platinum',
      'TPBank World Mastercard',
      'TPBank JCB',
      'TPBank EVO',
    ],
  },
  {
    code: 'SHB',
    name: 'SHB',
    fullName: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    logo: logo('shb.com.vn'),
    color: '#652C8F',
    description: 'Ngân hàng Sài Gòn - Hà Nội',
    website: 'https://www.shb.com.vn',
    hotline: '1800588856',
    cardBrands: [V, M],
    creditCards: ['SHB Visa Platinum', 'SHB Mastercard', 'SHB Family'],
  },
  {
    code: 'MSB',
    name: 'MSB',
    fullName: 'Ngân hàng TMCP Hàng Hải Việt Nam',
    logo: logo('msb.com.vn'),
    color: '#E4002B',
    description: 'Ngân hàng Hàng Hải Việt Nam',
    website: 'https://www.msb.com.vn',
    hotline: '1800599999',
    cardBrands: [V, M],
    creditCards: ['MSB Visa Online', 'MSB mDigi', 'MSB Visa Signature', 'MSB Travel'],
  },
  {
    code: 'OCB',
    name: 'OCB',
    fullName: 'Ngân hàng TMCP Phương Đông',
    logo: logo('ocb.com.vn'),
    color: '#006B3F',
    description: 'Ngân hàng Phương Đông',
    website: 'https://www.ocb.com.vn',
    hotline: '18006678',
    cardBrands: [V, M],
    creditCards: ['OCB Mastercard', 'OCB Visa Platinum', 'OCB Installment'],
  },
  {
    code: 'SeABank',
    name: 'SeABank',
    fullName: 'Ngân hàng TMCP Đông Nam Á',
    logo: logo('seabank.com.vn'),
    color: '#E4002B',
    description: 'Ngân hàng Đông Nam Á',
    website: 'https://www.seabank.com.vn',
    hotline: '1900555587',
    cardBrands: [V, M],
    creditCards: ['SeABank Visa Platinum', 'SeABank Mastercard', "SeABank S'Card"],
  },
  {
    code: 'LPBank',
    name: 'LPBank',
    fullName: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    logo: logo('lpbank.com.vn'),
    color: '#C8102E',
    description: 'Ngân hàng Lộc Phát Việt Nam',
    website: 'https://www.lpbank.com.vn',
    hotline: '1800577758',
    cardBrands: [V, M, J],
    creditCards: ['LPBank Visa', 'LPBank Mastercard', 'LPBank JCB'],
  },
  {
    code: 'EIB',
    name: 'Eximbank',
    fullName: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    logo: logo('eximbank.com.vn'),
    color: '#00539B',
    description: 'Ngân hàng Xuất Nhập khẩu Việt Nam',
    website: 'https://www.eximbank.com.vn',
    hotline: '1800111118',
    cardBrands: [V, M, J],
    creditCards: ['Eximbank Visa Platinum', 'Eximbank Mastercard', 'Eximbank JCB'],
  },
  {
    code: 'SCB',
    name: 'SCB',
    fullName: 'Ngân hàng TMCP Sài Gòn',
    logo: logo('scb.com.vn'),
    color: '#1B3A6B',
    description: 'Ngân hàng Sài Gòn',
    website: 'https://www.scb.com.vn',
    hotline: '1900545438',
    cardBrands: [V, M],
    creditCards: ['SCB Visa', 'SCB Mastercard', 'SCB S-Care'],
  },
  {
    code: 'NamABank',
    name: 'Nam A Bank',
    fullName: 'Ngân hàng TMCP Nam Á',
    logo: logo('namabank.com.vn'),
    color: '#0067B1',
    description: 'Ngân hàng Nam Á',
    website: 'https://www.namabank.com.vn',
    hotline: '1900656266',
    cardBrands: [V, M],
    creditCards: ['Nam A Bank Visa', 'Nam A Bank Mastercard'],
  },
  {
    code: 'ABBank',
    name: 'ABBANK',
    fullName: 'Ngân hàng TMCP An Bình',
    logo: logo('abbank.vn'),
    color: '#005BAC',
    description: 'Ngân hàng An Bình',
    website: 'https://www.abbank.vn',
    hotline: '1800571800',
    cardBrands: [V, M],
    creditCards: ['ABBANK Visa', 'ABBANK YOUcard'],
  },
  {
    code: 'BacABank',
    name: 'Bac A Bank',
    fullName: 'Ngân hàng TMCP Bắc Á',
    logo: logo('baca-bank.vn'),
    color: '#00674A',
    description: 'Ngân hàng Bắc Á',
    website: 'https://www.baca-bank.vn',
    hotline: '1800588828',
    cardBrands: [M],
    creditCards: ['Bac A Bank Mastercard'],
  },
  {
    code: 'PVcomBank',
    name: 'PVcomBank',
    fullName: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    logo: logo('pvcombank.com.vn'),
    color: '#E2231A',
    description: 'Ngân hàng Đại Chúng Việt Nam',
    website: 'https://www.pvcombank.com.vn',
    hotline: '1900555592',
    cardBrands: [V, M],
    creditCards: ['PVcomBank Mastercard', 'PVcomBank Visa'],
  },
  {
    code: 'VietABank',
    name: 'VietABank',
    fullName: 'Ngân hàng TMCP Việt Á',
    logo: logo('vietabank.com.vn'),
    color: '#00833E',
    description: 'Ngân hàng Việt Á',
    website: 'https://www.vietabank.com.vn',
    hotline: '1900555590',
    cardBrands: [M],
    creditCards: ['VietABank Mastercard'],
  },
  {
    code: 'KLB',
    name: 'KienlongBank',
    fullName: 'Ngân hàng TMCP Kiên Long',
    logo: logo('kienlongbank.com'),
    color: '#005EA6',
    description: 'Ngân hàng Kiên Long',
    website: 'https://www.kienlongbank.com',
    hotline: '1900633349',
    cardBrands: [V, J],
    creditCards: ['KienlongBank JCB', 'KienlongBank Visa'],
  },
  {
    code: 'BaoVietBank',
    name: 'BaoViet Bank',
    fullName: 'Ngân hàng TMCP Bảo Việt',
    logo: logo('baovietbank.vn'),
    color: '#00558C',
    description: 'Ngân hàng Bảo Việt',
    website: 'https://www.baovietbank.vn',
    hotline: '1900558848',
    cardBrands: [M],
    creditCards: ['BaoViet Bank Mastercard'],
  },
  {
    code: 'SGB',
    name: 'Saigonbank',
    fullName: 'Ngân hàng TMCP Sài Gòn Công Thương',
    logo: logo('saigonbank.com.vn'),
    color: '#1B458F',
    description: 'Ngân hàng Sài Gòn Công Thương',
    website: 'https://www.saigonbank.com.vn',
    hotline: '1900555585',
    cardBrands: [M],
    creditCards: [],
  },
  {
    code: 'VietBank',
    name: 'VietBank',
    fullName: 'Ngân hàng TMCP Việt Nam Thương Tín',
    logo: logo('vietbank.com.vn'),
    color: '#E4002B',
    description: 'Ngân hàng Việt Nam Thương Tín',
    website: 'https://www.vietbank.com.vn',
    hotline: '1800585855',
    cardBrands: [V, M],
    creditCards: ['VietBank Visa', 'VietBank Mastercard'],
  },
  {
    code: 'NCB',
    name: 'NCB',
    fullName: 'Ngân hàng TMCP Quốc Dân',
    logo: logo('ncb-bank.vn'),
    color: '#ED1C24',
    description: 'Ngân hàng Quốc Dân',
    website: 'https://www.ncb-bank.vn',
    hotline: '1800599868',
    cardBrands: [M],
    creditCards: ['NCB Mastercard'],
  },
  {
    code: 'PGBank',
    name: 'PGBank',
    fullName: 'Ngân hàng TMCP Thịnh vượng và Phát triển',
    logo: logo('pgbank.com.vn'),
    color: '#F37021',
    description: 'Ngân hàng Thịnh vượng và Phát triển',
    website: 'https://www.pgbank.com.vn',
    hotline: '1900555574',
    cardBrands: [V],
    creditCards: ['PGBank Visa'],
  },
  {
    code: 'BVBank',
    name: 'BVBank',
    fullName: 'Ngân hàng TMCP Bản Việt',
    logo: logo('bvbank.net.vn'),
    color: '#005BAB',
    description: 'Ngân hàng Bản Việt',
    website: 'https://www.bvbank.net.vn',
    hotline: '1900555596',
    cardBrands: [V, M],
    creditCards: ['BVBank Visa', 'BVBank Mastercard'],
  },
  // ── Foreign / wholly-owned banks in Vietnam ───────────────────────────────
  {
    code: 'HSBC',
    name: 'HSBC',
    fullName: 'Ngân hàng TNHH MTV HSBC Việt Nam',
    logo: logo('hsbc.com.vn'),
    color: '#DB0011',
    description: 'HSBC Việt Nam',
    website: 'https://www.hsbc.com.vn',
    hotline: '1900588866',
    cardBrands: [V, M],
    creditCards: [
      'HSBC Visa Cash Back',
      'HSBC Live+',
      'HSBC Premier World Mastercard',
      'HSBC TravelOne',
      'HSBC Visa Platinum',
    ],
  },
  {
    code: 'SCBank',
    name: 'Standard Chartered',
    fullName: 'Ngân hàng TNHH MTV Standard Chartered Việt Nam',
    logo: logo('sc.com'),
    color: '#0473EA',
    description: 'Standard Chartered Việt Nam',
    website: 'https://www.sc.com/vn',
    hotline: '1800558868',
    cardBrands: [V, M],
    creditCards: [
      'Standard Chartered WorldMiles',
      'Standard Chartered Visa Platinum',
      'Standard Chartered Smart',
    ],
  },
  {
    code: 'Shinhan',
    name: 'Shinhan Bank',
    fullName: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    logo: logo('shinhan.com.vn'),
    color: '#0046A0',
    description: 'Shinhan Bank Việt Nam',
    website: 'https://www.shinhan.com.vn',
    hotline: '1900151515',
    cardBrands: [V, M],
    creditCards: [
      'Shinhan Visa Platinum',
      'Shinhan Cashback',
      'Shinhan Hi-Point',
      'Shinhan e-Card',
      'Shinhan Travel Platinum',
    ],
  },
  {
    code: 'UOB',
    name: 'UOB',
    fullName: 'Ngân hàng TNHH MTV United Overseas Bank Việt Nam',
    logo: logo('uob.com.vn'),
    color: '#005DAA',
    description: 'United Overseas Bank Việt Nam',
    website: 'https://www.uob.com.vn',
    hotline: '1800558880',
    cardBrands: [V, M],
    creditCards: ["UOB Privi Miles", "UOB Lady's Card", 'UOB One Card', 'UOB EVOL'],
  },
  {
    code: 'Woori',
    name: 'Woori Bank',
    fullName: 'Ngân hàng TNHH MTV Woori Việt Nam',
    logo: logo('wooribank.com.vn'),
    color: '#0067AC',
    description: 'Woori Bank Việt Nam',
    website: 'https://www.wooribank.com.vn',
    hotline: '1900545463',
    cardBrands: [V, M],
    creditCards: ['Woori Visa', 'Woori Mastercard'],
  },
  {
    code: 'PublicBank',
    name: 'Public Bank',
    fullName: 'Ngân hàng TNHH MTV Public Việt Nam',
    logo: logo('publicbank.com.vn'),
    color: '#D71920',
    description: 'Public Bank Việt Nam',
    website: 'https://www.publicbank.com.vn',
    hotline: '1900633979',
    cardBrands: [V, M],
    creditCards: ['Public Bank Visa', 'Public Bank Mastercard'],
  },
  {
    code: 'CIMB',
    name: 'CIMB',
    fullName: 'Ngân hàng TNHH MTV CIMB Việt Nam',
    logo: logo('cimbbank.com.vn'),
    color: '#7A0019',
    description: 'CIMB Việt Nam',
    website: 'https://www.cimbbank.com.vn',
    hotline: '1900966989',
    cardBrands: [V, M],
    creditCards: ['CIMB Visa', 'CIMB Mastercard'],
  },
];
